// <auto-generated />
using System;
using CharacterBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterBook.Data.Migrations
{
    [DbContext(typeof(HoLDbContext))]
    [Migration("20240422164602_ChangeCharacterAndProfessionData")]
    partial class ChangeCharacterAndProfessionData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterBook.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ag_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("Ag_Primar")
                        .HasColumnType("int");

                    b.Property<bool>("Ag_bool")
                        .HasColumnType("bit");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Cha_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("Cha_Primar")
                        .HasColumnType("int");

                    b.Property<bool>("Cha_bool")
                        .HasColumnType("bit");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Co_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("Co_Primar")
                        .HasColumnType("int");

                    b.Property<bool>("Con_bool")
                        .HasColumnType("bit");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("In_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("In_Primar")
                        .HasColumnType("int");

                    b.Property<bool>("Int_bool")
                        .HasColumnType("bit");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("St_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("St_Primar")
                        .HasColumnType("int");

                    b.Property<bool>("St_bool")
                        .HasColumnType("bit");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ag_DiceRoll = 4,
                            Ag_Primar = 2,
                            Ag_bool = true,
                            Agility = 0,
                            Cha_DiceRoll = 4,
                            Cha_Primar = 0,
                            Cha_bool = false,
                            Charisma = 0,
                            Co_DiceRoll = 4,
                            Co_Primar = 2,
                            Con_bool = false,
                            Constitution = 0,
                            Description = "Drobný hobit pocházející z Kraje za Hvozdem.",
                            In_DiceRoll = 4,
                            In_Primar = 2,
                            Int_bool = false,
                            Intelligence = 0,
                            Name = "Bilbo Pytlík",
                            ProfessionId = 1,
                            RaceId = 1,
                            St_DiceRoll = 4,
                            St_Primar = 2,
                            St_bool = true,
                            Strength = 0
                        });
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Fight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Narrative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NarrativeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NarrativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorldId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Naratives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Era = "Císaře C-Chou",
                            NarrativeDescription = "Příběh ve vzdálené číně",
                            NarrativeName = "Čína",
                            WorldId = 1,
                            Year = 679
                        },
                        new
                        {
                            Id = 2,
                            Era = "III",
                            NarrativeDescription = "Boje v Persii",
                            NarrativeName = "Řecko",
                            WorldId = 1,
                            Year = 679
                        },
                        new
                        {
                            Id = 3,
                            Era = "XXI",
                            NarrativeDescription = "podle Pc hry",
                            NarrativeName = "Warhammer",
                            WorldId = 2,
                            Year = 3754
                        });
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Profession", b =>
                {
                    b.Property<int>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessionId"));

                    b.Property<int>("AtributePointed")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GetHpDiceRoll")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GetProfessionPointedDiceRoll")
                        .HasColumnType("int");

                    b.Property<bool>("HpAllDiceRolls")
                        .HasColumnType("bit");

                    b.Property<int>("HpPointeded")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("ManaAlchemistBool")
                        .HasColumnType("bit");

                    b.Property<bool>("ManaRengerBool")
                        .HasColumnType("bit");

                    b.Property<bool>("ManaWizardBool")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NarrativId")
                        .HasColumnType("int");

                    b.Property<int?>("NarrativeId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessionPoint")
                        .HasColumnType("int");

                    b.HasKey("ProfessionId");

                    b.HasIndex("NarrativeId");

                    b.ToTable("Professions");

                    b.HasData(
                        new
                        {
                            ProfessionId = 1,
                            AtributePointed = 25,
                            Description = "Válečník je silný a houževnatý. Vládne mnoha druhy zbraní a umí se v jejich používání zdokonalovat. V boji má větší šanci, že nepřítele zasáhne. A vzhledem k tomu, že bitvy a souboje jsou v Dračím doupěti běžné, je pro každou družinu nezbytné, aby ve svém středu měla jednoho nebo více válečníků. Postavy jiných povolání sice také mohou bojovat, ale mohou být svázány rozličnými omezeními. Válečníci jsou jediní, kteří boj skutečně studují a mají v něm některé výhody, které žádné jiné povolání nemá.",
                            GetHpDiceRoll = "[10]",
                            GetProfessionPointedDiceRoll = 1,
                            HpAllDiceRolls = true,
                            HpPointeded = 4,
                            Level = 3,
                            ManaAlchemistBool = false,
                            ManaRengerBool = false,
                            ManaWizardBool = false,
                            Name = "Válečník",
                            NarrativId = 1,
                            ProfessionPoint = 18
                        },
                        new
                        {
                            ProfessionId = 2,
                            AtributePointed = 24,
                            Description = "Hraničář je silný a moudrý. Zná přírodu a tvory, kteří ji obývají, a umí svých znalostí využívat. V boji má určitá omezení, ale stále může být platným bojovníkem po boku válečníka. Kromě toho je vhodný jako silná zadní stráž v družinách, které nemají dost válečníků (a takových družin bude většina).\r\nHraničáři zpravidla žijí v hlubokých hvozdech, kde sami, jen se svými psy, střeží stezky a pomáhají těm, kdo pomoc potřebují. Proto jsou takřka všude vítanými hosty. Dlouholetým stykem s přírodou a přírodní magií se u nich vyvíjejí i jisté nadpřirozené schopnosti, které jim pomáhají při jejich nebezpečném a osamoceném životě alespoň tak se to mezi lidmi povídá.\r\nHraničáři se dají přemluvit, aby se připojili k družině. Jsou vynikajícími lovci a stopaři a proto jsou neocenitelní při dobrodružstvích ve volné přírodě. Ale jejich mimořádné schopnosti jsou užitečné i jinde, například v podzemí. V boji i mimo něj je hraničář hodnotným členem každé družiny.\r\n",
                            GetHpDiceRoll = "[6]",
                            GetProfessionPointedDiceRoll = 4,
                            HpAllDiceRolls = true,
                            HpPointeded = 1,
                            Level = 1,
                            ManaAlchemistBool = false,
                            ManaRengerBool = true,
                            ManaWizardBool = false,
                            Name = "Hraničář",
                            NarrativId = 1,
                            ProfessionPoint = 21
                        },
                        new
                        {
                            ProfessionId = 3,
                            AtributePointed = 27,
                            Description = "Alchymista je šikovný a leccos vydrží. Zabývá se výrobou lektvarů a různých kouzelných předmětů. V boji většinou nepomáhá přímo, ale prostřednictvím svého umění. Alchymisté se liší od kouzelníků svým přístupem k magii. Zatímco kouzelníci rozvíjejí svou inteligenci a z ní získávají magenergii, alchymisté ji destilují z různých předmětů a záleží jen na jejich obratnosti, zda a kolik magenergie se jim z nich podaří vytěžit.\r\nDíky tomu jsou alchymisté bližší \"obyčejným\" lidem než kouzelníci a nevzbuzují u nich strach. Přesto mají svým způsobem mnohem důvěrnější vztah k magenergii než jiná povolání nadaná schopností kouzlit.\r\nAlchymistovy kouzelné předměty mohou být užitečné v mnoha různých situacích. Jejich účinky se často liší od účinků kouzelníkových kouzel a žádná družina neprodělá, když bude mít alchymistu ve svém středu.\r\n",
                            GetHpDiceRoll = "[6]",
                            GetProfessionPointedDiceRoll = 6,
                            HpAllDiceRolls = true,
                            HpPointeded = 2,
                            Level = 1,
                            ManaAlchemistBool = true,
                            ManaRengerBool = false,
                            ManaWizardBool = false,
                            Name = "Alchymista",
                            NarrativId = 1,
                            ProfessionPoint = 23
                        },
                        new
                        {
                            ProfessionId = 4,
                            AtributePointed = 24,
                            Description = "Kouzelník je chytrý a umí ovlivňovat druhé. Není příliš silný v boji, ale vynahrazuje si to svými zvláštními schopnostmi, zejména studiem kouzel. Kouzelníci byli vždy terčem nejrůznějších dohadů a nikdo vlastně neví, co všechno mohou dokázat. Lidé se k nim chovají uctivě, ale podezřívavě a se strachem. Kouzelníci sami dávají přednost samotě, ve které studují svá kouzla, a stýkají se jenom se svým učitelem.\r\nKouzla jsou přirozenou so částí světa. Jsou předměty, které jsou bezcenné pro někoho, kdo se v kouzlech nevyzná, a které se mohou stát strašnou zbraní v rukou mága.\r\nŘadu situaci je mnohem lehčí vyřešit pomoci kouzla než obvyklým způsobem. Ale pozor! Nejde to vždy a zvláště zpočátku jsou kouzla spíše vzácná.\r\nPro své mimořádné schopnosti je kouzelník vyhledávaným členem každé družiny. Je pravda, že většinu času alespoň zpočátku - zůstávají tyto schopnosti nevyužity, ale okamžik, kdy je použije, může znamenat rozhodující zvrat v celém dobrodružství.\r\n",
                            GetHpDiceRoll = "[6]",
                            GetProfessionPointedDiceRoll = 2,
                            HpAllDiceRolls = true,
                            HpPointeded = 1,
                            Level = 1,
                            ManaAlchemistBool = false,
                            ManaRengerBool = false,
                            ManaWizardBool = true,
                            Name = "Kouzelník",
                            NarrativId = 1,
                            ProfessionPoint = 19
                        },
                        new
                        {
                            ProfessionId = 5,
                            AtributePointed = 25,
                            Description = "Zloděj je mrštný a umí se vloudit do přízně jiných lidí. V boji zpravidla nestojí v první řadě a není to ani jeho poslání, ale dokáže i tvrdě zasáhnout.\r\nZloději jsou odborníky na nebezpečné situace, které vyžadují vtip a obratnost místo hrubé síly. Zloději studují své řemeslo v obávaném zlodějském cechu a prostí lidé si vyprávějí bájné zkazky o jejich umění. O zlodějích, kteří sami pronikli do přísně střežených pevností nebo zakletých hrobek a ukradli královské poklady, o zlodějích, kteří unikli z okovů v podzemním žaláři, hlídaném těmi nejlepšími z královské gardy.\r\nZloději z pochopitelných důvodů jen neradi odhalují svou profesi. Dokážou být velice zábavní společníci, snadno si získají přízeň jiných lidí a zjisti tak množství zajímavých informaci. Ty pak využijí ke svému prospěchu, nebo k prospěchu družiny.\r\nDíky svým pozoruhodným schopnostem, které nemá žádné jiné povolání, je zloděj žádaným členem v každé družině. Postavám, se kterými půjde, ušetří mnoho nesnází.\r\n",
                            GetHpDiceRoll = "[6]",
                            GetProfessionPointedDiceRoll = 3,
                            HpAllDiceRolls = true,
                            HpPointeded = 1,
                            Level = 1,
                            ManaAlchemistBool = false,
                            ManaRengerBool = false,
                            ManaWizardBool = false,
                            Name = "Zloděj",
                            NarrativId = 1,
                            ProfessionPoint = 20
                        });
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Agility_Corection")
                        .HasColumnType("int");

                    b.Property<int>("Agility_Max")
                        .HasColumnType("int");

                    b.Property<int>("BodyHeightMax")
                        .HasColumnType("int");

                    b.Property<int>("BodyHeightMin")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Charisma_Correction")
                        .HasColumnType("int");

                    b.Property<int>("Charisma_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("Charisma_Max")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Constitution_Corection")
                        .HasColumnType("int");

                    b.Property<int>("Constitution_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("Constitution_Max")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity_DiceRoll")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence_Correction")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence_Max")
                        .HasColumnType("int");

                    b.Property<int>("Mobility")
                        .HasColumnType("int");

                    b.Property<string>("RaceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceSize")
                        .HasColumnType("int");

                    b.Property<string>("SpecialAbilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialAbilitiesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Strength_Corection")
                        .HasColumnType("int");

                    b.Property<int>("Strength_DiceRoll")
                        .HasColumnType("int");

                    b.Property<int>("Strength_Max")
                        .HasColumnType("int");

                    b.Property<int>("WeightMax")
                        .HasColumnType("int");

                    b.Property<int>("WeightMin")
                        .HasColumnType("int");

                    b.HasKey("RaceId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            Agility = 11,
                            Agility_Corection = 2,
                            Agility_Max = 16,
                            BodyHeightMax = 120,
                            BodyHeightMin = 70,
                            Charisma = 8,
                            Charisma_Correction = 3,
                            Charisma_DiceRoll = 2,
                            Charisma_Max = 18,
                            Constitution = 8,
                            Constitution_Corection = 0,
                            Constitution_DiceRoll = 1,
                            Constitution_Max = 13,
                            Dexterity_DiceRoll = 1,
                            ImagePath = "~/Images/Race/hobbit.jpeg",
                            Intelligence = 10,
                            Intelligence_Correction = -2,
                            Intelligence_DiceRoll = 1,
                            Intelligence_Max = 15,
                            Mobility = 10,
                            RaceDescription = "Hobiti jsou malým, veselým nárůdkem. Jsou ještě menší než trpaslíci, chlupatí a jaksi \"dobrácky kulaťoučcí\". Žijí zpravidla v úrodných údolích, kde si ve stráních budují komfortní nory a doupata. Rozhodně nejsou nijak zvlášť silní, ale zato jsou velmi obratní a povětšinou inteligentní. Dobrodružství příliš nevyhledávají, protože mají rádi pohodlí, dobré jídlo a silné piti. Jestliže se však jednou přece jen vydají na cesty, patří k těm nejlepším zlodějům, jaké si jen dovedeš představit. Hobiti mají také zvláštní psychickou schopnost, díky které dokážou \"vycítit\" na dálku většinu živých tvorů. Této zvláštní vlastnosti říkají mezi sebou \"čich\", a přestože jejich pohodlnickým životem již dosti zakrněla, dokážou díky ní lokalizovat živou bytost, dokonce i když je od nich oddělena například železnou stěnou. Přestože hobiti nejsou zbabělí, jen neradi přistupují na boj tváří v tvář a raději používají své kuše než těžké meče nebo halapartny.",
                            RaceName = "Hobbit",
                            RaceSize = 0,
                            SpecialAbilities = "Čich",
                            SpecialAbilitiesDescription = "Tato schopnost mu umožňuje vycítit přítomnost většiny živých tvorů což zdaleka neznamená všechny tvory, například na kostlivce je hobitův čich krátký), není ale schopen vycítit různé plísně, houby a jiné rostliny ani běžné tvory velikosti A0 (respektive byl by schopen je cítit, ale nevnímá je, asi jako člověk obvykle nevnímá mravence v trávě, ačkoliv je schopen je vidět). Největší vzdálenost, na jakou to je schopen dokázat, je 12 sáhů. Tato vzdálenost se zkracuje o 1 sáh za každých 30 coulů dřeva, 10 coulů kamene nebo 1 coul kovu. Hobit není schopen určit, o jakého tvora se jedná, ani jak je přesně daleko, ale pozná, do jaké třídy velikosti patří. Hobit má neurčitý pocit cizí přítomnosti. Hobit nemůže svou zvláštní schopnost používat, pokud spí. V bdělém stavu se na ni nemusí soustředit, ale nebude-li svému okolí věnovat dostatečnou pozornost, může mu něco uniknout. Hobita při používání čichu neruší přítomnost ostatních členů družiny.",
                            Strength = 3,
                            Strength_Corection = -5,
                            Strength_DiceRoll = 1,
                            Strength_Max = 8,
                            WeightMax = 60,
                            WeightMin = 40
                        },
                        new
                        {
                            RaceId = 2,
                            Agility = 10,
                            Agility_Corection = 1,
                            Agility_Max = 15,
                            BodyHeightMax = 130,
                            BodyHeightMin = 90,
                            Charisma = 7,
                            Charisma_Correction = 0,
                            Charisma_DiceRoll = 1,
                            Charisma_Max = 12,
                            Constitution = 10,
                            Constitution_Corection = 1,
                            Constitution_DiceRoll = 1,
                            Constitution_Max = 15,
                            Dexterity_DiceRoll = 1,
                            ImagePath = "~/Images/Race/gnom.jpeg",
                            Intelligence = 9,
                            Intelligence_Correction = -2,
                            Intelligence_DiceRoll = 1,
                            Intelligence_Max = 14,
                            Mobility = 9,
                            RaceDescription = "Gnómové jsou zvláštní rasou, o které se ví téměř jistě, že vznikla kdysi v dávných dobách splynutím části plemene trpaslíků s hobity. Podobně jako hobiti také gnómové jsou velmi obratní a poměrně chytří. Po trpaslících zase zdědili jejich nezdolnost a z části také lásku ke zlatu a drahým kamenům. Žijí v horách i v nížinách, ale nemilují podzemí, a proto si staví drobné kamenné domy, většinou daleko od velkých měst a obchodních cest. Přestože jen málokterý z nich se stane dobrým bojovníkem, dokážou v boji velmi dobře zacházet jak se sekerou, tak i s kuší. Mnoho z nich také nachází potěšení v různém bylinkářství a alchymii, ale stejně tak dobře se mohou uplatnit třeba jako zloději.",
                            RaceName = "Gnom",
                            RaceSize = 0,
                            SpecialAbilities = "",
                            SpecialAbilitiesDescription = "",
                            Strength = 5,
                            Strength_Corection = -3,
                            Strength_DiceRoll = 1,
                            Strength_Max = 10,
                            WeightMax = 75,
                            WeightMin = 50
                        },
                        new
                        {
                            RaceId = 3,
                            Agility = 7,
                            Agility_Corection = -2,
                            Agility_Max = 12,
                            BodyHeightMax = 140,
                            BodyHeightMin = 110,
                            Charisma = 7,
                            Charisma_Correction = -2,
                            Charisma_DiceRoll = 1,
                            Charisma_Max = 12,
                            Constitution = 12,
                            Constitution_Corection = 3,
                            Constitution_DiceRoll = 1,
                            Constitution_Max = 17,
                            Dexterity_DiceRoll = 1,
                            ImagePath = "~/Images/Race/trpaslik.jpeg",
                            Intelligence = 8,
                            Intelligence_Correction = -3,
                            Intelligence_DiceRoll = 1,
                            Intelligence_Max = 13,
                            Mobility = 8,
                            RaceDescription = "Trpaslíci jsou jednou z nejznámějších člověku podobných ras. Jsou menší, podsadití, zocelení dlouhými věky strávenými v nehostinných pustinách. Jejich větrem ošlehané tváře snad vždy zdobí hnědé až černé vousy, které jim však, stejně jako vlasy, poměrně záhy šedivějí. Sídlí v horách, zpravidla daleko od civilizace. Díky infravidění vidí v omezené míře i ve tmě, a proto mohou pod zemí budovat rozsáhlé skalní komplexy šachet, jeskyní a sálů, kde těží drahé kameny, stříbro a především svoje milované zlato. Trpaslíci většinou postrádají jakýkoliv smysl pro humor, jsou vždy vážní a někdy až příliš sebejistí. Dané slovo dodrží, zejména kyne-li jim z toho nějaká výhoda. Jejich nejoblíbenější zbraní je válečná sekera. V boji jsou nesmírně stateční a jen neradi ustupují z prohrané bitvy. Brání-li trpaslík svoji hroudu zlata, neustoupí ani před rozvztekleným, vyhladovělým ohnivým drakem.",
                            RaceName = "Trpaslík",
                            RaceSize = 0,
                            SpecialAbilities = "Infravidění",
                            SpecialAbilitiesDescription = "Infravidění má dosah 20 sáhů a neproniká žádným materiálem, kterým by neproniklo obyčejné světlo. Ve slunečním světle (nebo ve světle stejné intenzity vyvolaném kouzlem) je infravidění nepoužitelné. Infravidění rovněž není použitelné za mlhy (a to ani ve tmě), podobně jako normální zrak. Pod vodou je infravidění použitelné, ale nikoli skrz vodní hladinu, která infrazáření podobně jako světlo a zvuk láme a všelijak zkresluje. Infravidění je schopnost vidět teplo. I v naprosté tmě trpaslík zřetelně uvidí každého živého tvora s teplou krví - skřeta i zatoulaného psa- jako jasně červenou skvrnu. Hady, červy a jiné studenokrevné živočichy trpaslík neuvidí, pokud se nebude dívat velmi pozorně. Infraviděním rovněž nelze zpozorovat některé nestvůry magické podstaty, jež nevydávají teplo (například kostlivce). lnfraviděním zpravidla nelze určovat ani tvar místností, ani jejich obsah. Výjimkou mohou být věci, které jsou studenější nebo teplejší než okolí. Například jezírko studené vody trpaslík uvidí jako tmavě modrou skvrnu, nedávno vyhaslé ohniště jako tmavě červenou. Trpaslík se nemusí na infravidění soustřeďovat. V situaci, kdy mu nebude stačit obyčejný zrak, začne automaticky infravidění využívat. I když tobě se takové zobrazení může zdát nejasné a nepochopitelné, trpaslík, který ho má jako vrozenou schopnost, se v něm poměrně dobře vyzná. Přechod od normálního vidění k infra vidění lze přirovnat k překrývání fotografií. Jakmile v šeru trpaslík přestává vidět skutečné barvy, začíná vnímat infrabarvy.",
                            Strength = 7,
                            Strength_Corection = 1,
                            Strength_DiceRoll = 1,
                            Strength_Max = 12,
                            WeightMax = 100,
                            WeightMin = 55
                        },
                        new
                        {
                            RaceId = 4,
                            Agility = 10,
                            Agility_Corection = 1,
                            Agility_Max = 15,
                            BodyHeightMax = 180,
                            BodyHeightMin = 145,
                            Charisma = 8,
                            Charisma_Correction = 2,
                            Charisma_DiceRoll = 2,
                            Charisma_Max = 18,
                            Constitution = 6,
                            Constitution_Corection = -4,
                            Constitution_DiceRoll = 1,
                            Constitution_Max = 11,
                            Dexterity_DiceRoll = 1,
                            ImagePath = "~/Images/Race/elf.jpeg",
                            Intelligence = 12,
                            Intelligence_Correction = 2,
                            Intelligence_DiceRoll = 1,
                            Intelligence_Max = 17,
                            Mobility = 12,
                            RaceDescription = "Elfové jsou známou rasou, žijící zpravidla hluboko v lesích nebo odlehlých údolích a roklinách. Jsou menší než lidé a zdaleka ne tak robustní. Pro své většinou plavé vlasy a jemné rysy obličeje jsou pokládáni za velmi krásné až poněkud změkčilé. Protože jsou velmi inteligentní, jen neradi bojují avšak jsou-li k boji donuceni, mohou být nebezpečnými soupeři. Díky své obratnosti dovedou dobře zacházet zejména s lukem a se střelnými zbraněmi vůbec. Největší potěšeni jim však činí studium a učení se kouzlům, a proto z jejich řad vzešlo již mnoho známých kouzelníků. Také milují krásné věci, ale od trpaslíků (které mimochodem nemají příliš v lásce) se liší především tím, že krásu hned nepřepočítávají na zlaťáky. Elfové jsou vesměs velmi čestní a spravedliví a nikdy se mezi nimi nevyskytují jedinci, pro které by zlo bylo přirozenou podstatou jejich osobnosti.",
                            RaceName = "Elf",
                            RaceSize = 1,
                            SpecialAbilities = "Dlouhověkost",
                            SpecialAbilitiesDescription = "",
                            Strength = 6,
                            Strength_Corection = 0,
                            Strength_DiceRoll = 1,
                            Strength_Max = 11,
                            WeightMax = 85,
                            WeightMin = 50
                        },
                        new
                        {
                            RaceId = 5,
                            Agility = 9,
                            Agility_Corection = 0,
                            Agility_Max = 14,
                            BodyHeightMax = 210,
                            BodyHeightMin = 165,
                            Charisma = 2,
                            Charisma_Correction = 0,
                            Charisma_DiceRoll = 3,
                            Charisma_Max = 17,
                            Constitution = 9,
                            Constitution_Corection = 0,
                            Constitution_DiceRoll = 1,
                            Constitution_Max = 14,
                            Dexterity_DiceRoll = 1,
                            ImagePath = "~/Images/Race/clovek.jpeg",
                            Intelligence = 10,
                            Intelligence_Correction = 0,
                            Intelligence_DiceRoll = 1,
                            Intelligence_Max = 15,
                            Mobility = 11,
                            RaceDescription = "Lidé jsou snad nejrozšířenější rasou, žijící jak v oblastech hor, tak i ve stepích, lesích a tundrách. Budují rozsáhlá sídla, ať už města či vesnice, která zpravidla leží na velkých obchodních křižovatkách. Lidé jsou velmi houževnatí, nacházejí uplatnění v celé škále povoláni. Většina z nich se zabývá především zemědělstvím a řemeslnou výrobou, ale najdete mezi nimi i zdatné lovce a zkušené dobrodruhy všeho druhu.",
                            RaceName = "Člověk",
                            RaceSize = 1,
                            SpecialAbilities = "",
                            SpecialAbilitiesDescription = "",
                            Strength = 6,
                            Strength_Corection = 0,
                            Strength_DiceRoll = 2,
                            Strength_Max = 16,
                            WeightMax = 115,
                            WeightMin = 65
                        },
                        new
                        {
                            RaceId = 6,
                            Agility = 8,
                            Agility_Corection = -1,
                            Agility_Max = 13,
                            BodyHeightMax = 220,
                            BodyHeightMin = 175,
                            Charisma = 1,
                            Charisma_Correction = -2,
                            Charisma_DiceRoll = 3,
                            Charisma_Max = 16,
                            Constitution = 11,
                            Constitution_Corection = 1,
                            Constitution_DiceRoll = 1,
                            Constitution_Max = 16,
                            Dexterity_DiceRoll = 1,
                            ImagePath = "~/Images/Race/barbar.jpeg",
                            Intelligence = 6,
                            Intelligence_Correction = 0,
                            Intelligence_DiceRoll = 1,
                            Intelligence_Max = 11,
                            Mobility = 12,
                            RaceDescription = "Barbaři jsou v podstatě lidé, ale jejich po staletí trvající odloučení od skutečné lidské civilizace způsobilo, že barbar zpravidla není tak inteligentní jako člověk, avšak je silnější a mnohem odolnější. Tyto vlastnosti jej také předurčují k tomu, aby se stal dobrým válečníkem.",
                            RaceName = "Barbar",
                            RaceSize = 1,
                            SpecialAbilities = "",
                            SpecialAbilitiesDescription = "",
                            Strength = 10,
                            Strength_Corection = 1,
                            Strength_DiceRoll = 1,
                            Strength_Max = 15,
                            WeightMax = 140,
                            WeightMin = 75
                        },
                        new
                        {
                            RaceId = 7,
                            Agility = 5,
                            Agility_Corection = -4,
                            Agility_Max = 10,
                            BodyHeightMax = 245,
                            BodyHeightMin = 180,
                            Charisma = 1,
                            Charisma_Correction = -5,
                            Charisma_DiceRoll = 2,
                            Charisma_Max = 11,
                            Constitution = 13,
                            Constitution_Corection = 3,
                            Constitution_DiceRoll = 1,
                            Constitution_Max = 18,
                            Dexterity_DiceRoll = 1,
                            ImagePath = "~/Images/Race/kroll.jpeg",
                            Intelligence = 2,
                            Intelligence_Correction = -6,
                            Intelligence_DiceRoll = 1,
                            Intelligence_Max = 7,
                            Mobility = 11,
                            RaceDescription = "Krollové sídlí v horách, tundrách a vůbec v prostředí velmi tvrdém a nehostinném. Dospělý kroll může měřit hodně přes dva metry a zjevem může vzdáleně (velmi vzdáleně) připomínat pračlověka, i když jeho kůže je spíše zrohovatělá než chlupatá. Bezpečně je však poznáte podle jejich nezaměnitelných uší, jimž vděčí za svůj neobvyklý sluch. Krollové jsou silnější než obyčejní lidé, ale také poněkud neohrabaní a zejména o poznání hloupější. Žijí obvykle v nevelkých kmenech, které mezi sebou neustále válčí. V těchto bojích se velmi zdokonalili, a proto nyní patří k nejobávanějším bojovníkům a z jejich kyjů a palcátů jde vskutku příslovečný strach. Po svých divokých předcích kromě jiného podědili také vrozený \"ultrasluch\", který jim umožňuje do jisté míry \"vidět\" (podobně jako netopýrům) i za úplné tmy nebo mlhy. Pokud jde o jejich původ, je možné, že vznikli kdysi dávno spojením skřeta s poloobrem. To by také vysvětlovalo, proč se mezi nimi téměř nikdy nevyskytují jedinci preferující výhradně dobro.",
                            RaceName = "Kroll",
                            RaceSize = 2,
                            SpecialAbilities = "Ultrasluch",
                            SpecialAbilitiesDescription = "Jeho zvláštní schopnost se nazývá ultrasluch a připomíná sonar netopýrů. Kroll je schopen vysílat Lidským uchem nezachytitelné zvukové vlnění, které se odráží od zkoumaného předmětu a vrací se zpět ke krollovi. Podle toho, jak odražené vlnění vypadá, je kroll schopen určit vzdálenost a tvar předmětu. Ultrasluch je použitelný v mlze, dokonce i pod vodou (ale ne skrz vodní hladinu, na ní se zvuk láme, odráží a všelijak zkresluje). Krollův ultrasluch má dosah 50 sáhů. To znamená, že kroll je schopen postřehnout jakýkoliv předmět nebo jakéhokoliv hmotného tvora, který je blíž než 50 sáhů a není zastíněn nějakým jiným předmětem nebo tvorem. Bude také schopen zhruba určit jeho vzdálenost a velikost. Kroll nepozná, o jakého tvora jde, ale pozná například, kolik má nohou apod. S předměty v jeskyni a jejím vybavením to je podobné. Krollův ultrasluch je v podstatě stále ještě sluchem, a proto závisí na hluku, který krolla obklopuje. Kroll nemůže používat ultrasluch v prostředí, které je hlučnější než obyčejný lidský hovor. Kroll svůj ultrasluch nepoužívá automaticky. Chce-li tuto svou zvláštní schopnost použít, musí o tom říct Pánovi jeskyně. Prozkoumávání ultrasluchem je stejně rychlé jako pohled. Prostor, který by kroll očima přehlédl během jednoho kola, je schopen za stejnou dobu prozkoumat i ultrasluchem. Kroll je schopen díky svému ultrasluchu vnímat i netopýry (a delfíny a jiné tvory, vybavené sonarem), není ovšem schopen se s nimi nijak dorozumět ani s nimi komunikovat. Tyto cizí signály krollův ultrasluch neruší, není-li jich příliš mnoho. Například uprostřed hejna netopýrů kroll svoji zvláštní schopnost může použít jen stěží.",
                            Strength = 11,
                            Strength_Corection = 3,
                            Strength_DiceRoll = 1,
                            Strength_Max = 16,
                            WeightMax = 200,
                            WeightMin = 100
                        });
                });

            modelBuilder.Entity("CharacterBook.Data.Models.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WorldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Worlds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WorldName = "Fantasy svět"
                        },
                        new
                        {
                            Id = 2,
                            WorldName = "Postapo"
                        },
                        new
                        {
                            Id = 3,
                            WorldName = "Reálný svět"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RaceWorld", b =>
                {
                    b.Property<int>("RacesRaceId")
                        .HasColumnType("int");

                    b.Property<int>("WorldsId")
                        .HasColumnType("int");

                    b.HasKey("RacesRaceId", "WorldsId");

                    b.HasIndex("WorldsId");

                    b.ToTable("RaceWorld");
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Character", b =>
                {
                    b.HasOne("CharacterBook.Data.Models.Profession", "Professions")
                        .WithMany("Character")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professions");
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Narrative", b =>
                {
                    b.HasOne("CharacterBook.Data.Models.World", "World")
                        .WithMany("Narratives")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Profession", b =>
                {
                    b.HasOne("CharacterBook.Data.Models.Narrative", "Narrative")
                        .WithMany("Professions")
                        .HasForeignKey("NarrativeId");

                    b.Navigation("Narrative");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceWorld", b =>
                {
                    b.HasOne("CharacterBook.Data.Models.Race", null)
                        .WithMany()
                        .HasForeignKey("RacesRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CharacterBook.Data.Models.World", null)
                        .WithMany()
                        .HasForeignKey("WorldsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Narrative", b =>
                {
                    b.Navigation("Professions");
                });

            modelBuilder.Entity("CharacterBook.Data.Models.Profession", b =>
                {
                    b.Navigation("Character");
                });

            modelBuilder.Entity("CharacterBook.Data.Models.World", b =>
                {
                    b.Navigation("Narratives");
                });
#pragma warning restore 612, 618
        }
    }
}
